FROM mysql:8.0

# Copiar o script de inicialização
COPY setup.sql /docker-entrypoint-initdb.d/

# Configurar variáveis de ambiente
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=login_db
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=password

# Expor a porta 3306
EXPOSE 3306 